# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.ohmyzsh]
dir = "plugins"
github = "ohmyzsh/ohmyzsh"
use = ["{git}/*.plugin.zsh"]

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
use = ["zsh-autocomplete.plugin.zsh"]
proto = "ssh"

