#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.anyenv/bin:$PATH"
export GOPATH="$HOME/go"
export PATH="$PATH:$HOME/.yarn/bin"
export EMOJI_CLI_KEYBIND="^x^e"
eval "$(anyenv init - zsh)"
export POWERLINE=$(pip show powerline-status | grep Location | sed -e "s/^Location: //")
[ -e $HOME/.dotfiles/zprivate ] && source $HOME/.dotfiles/zprivate 
