#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [ -f $(brew --prefix)/etc/brew-wrap ];then
  source $(brew --prefix)/etc/brew-wrap
fi

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.anyenv/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/others/flutter/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export EMOJI_CLI_KEYBIND="^x^f"
eval "$(anyenv init - zsh)"
[ -e $HOME/.dotfiles/zprivate ] && source $HOME/.dotfiles/zprivate

export YII_ENVIRONMENT=Test

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "b4b4r07/emoji-cli"
zplug load

source $HOME/.dotfiles/.zalias
source $HOME/.dotfiles/.zfunctions
