
# tap repositories and their packages

tap homebrew/core
brew chezmoi
brew fish
brew gh
brew ncurses
brew pcre2

tap homebrew/cask

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 803453959 Slack (4.35.130)
